---
title: "Maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(janitor)
library(plotly)
library(rnaturalearth)
library(tidyverse)
library(ggplot2)
library(rgeos)
```


```{r read in data, include = FALSE}

location_data <- read_csv("USRUS nuclear weapons info.csv", col_types = cols(
  Country = col_character(),
  `Base/location` = col_character(),
  Region = col_character(),
  `Weapon system` = col_character(),
  Remarks = col_character(),
  Type = col_character(),
  Lat = col_double(),
  Long = col_double()
)) %>% clean_names

location_data <- location_data %>% mutate(side = if_else(country == "Russia", "Russia", "United States"))

```


```{r make map}

world <- ne_countries(returnclass = "sf")

ggplot()+ 
  geom_sf(data = world, color = "gray", fill= "gray91")
  
  geom_point(data = location_data, aes(x =long, 
                                       y =lat, 
                                       color = type, 
                                       shape = type, 
                                       text = paste(
          "</br> Name: ", base_location,
          "</br> Delivery System: ", delivery_system,
          "</br> Warhead: ", warhead,
          "</br> Warhead type: ", type
        )))+
  scale_color_manual(values = c("NSNW" = "red", 
                               "Strategic" = "dodgerblue", 
                               "Strategic and NSNW" = "purple4", 
                               "ABM" = "springgreen4"))+ 
  labs(x = "", y = "")+
  theme(legend.position = c(0.8, 0.3), 
        legend.title = element_blank(), 
        legend.background = element_rect(fill = "white", color = "black"),
        legend.key = element_rect(fill = "white", color = "NA"))+
  theme(        panel.background = element_rect(fill = "lightsteelblue2"), 
        panel.grid.major = element_line(color = "lightsteelblue2"), 
        plot.margin = margin(0, 0, 0, 0, "cm"))

ggplotly(plot, width = 1200, height = 800, tooltip = "text") %>% 
  


```

```{r}


```


